const PHASES = [
  { num: 1, name: "Problem Definition", desc: "AI Data Analysis Automation scope & dataset schemas." },
  { num: 2, name: "System Architecture", desc: "Planner, Data, ML, Research, Reviewer, Report DAG topology." },
  { num: 3, name: "Agent Creation", desc: "Modular Python BaseAgent & specialized agent classes." },
  { num: 4, name: "LLM Integration", desc: "Multi-provider Gemini, OpenAI, Claude, & Local LLM layer." },
  { num: 5, name: "Tool Integration", desc: "Python execution, SQLite DB, REST API, Web Search & File Tools." },
  { num: 6, name: "Agent Communication", desc: "Automated state context propagation & message bus." },
  { num: 7, name: "Memory / RAG", desc: "VectorStore embeddings & RAG retrieval engine." },
  { num: 8, name: "Workflow Orchestration", desc: "LangGraph / CrewAI style DAG execution engine." },
  { num: 9, name: "Testing & Evaluation", desc: "Pytest suite, Zero-Hallucination auditor & quality scoring." },
  { num: 10, name: "Deployment & Monitoring", desc: "FastAPI REST API, Prometheus telemetry & Web Dashboard." }
];

document.addEventListener("DOMContentLoaded", () => {
  renderPhases();
  setupEventListeners();
});

function renderPhases() {
  const container = document.getElementById("phasesGrid");
  container.innerHTML = PHASES.map(p => `
    <div class="phase-card active">
      <div>
        <span class="phase-num">Phase ${p.num}</span>: <strong>${p.name}</strong>
      </div>
      <span>✅</span>
    </div>
  `).join("");
}

function setupEventListeners() {
  document.getElementById("runBtn").addEventListener("click", runCrewSimulation);
}

function logTerminal(msg) {
  const term = document.getElementById("logTerminal");
  const time = new Date().toLocaleTimeString();
  const line = document.createElement("div");
  line.className = "log-line";
  line.textContent = `[${time}] ${msg}`;
  term.appendChild(line);
  term.scrollTop = term.scrollHeight;
}

function clearLogs() {
  document.getElementById("logTerminal").innerHTML = "";
}

function setNodeActive(nodeId, isActive) {
  const el = document.getElementById(nodeId);
  if (el) {
    if (isActive) el.classList.add("active");
    else el.classList.remove("active");
  }
}

async function runCrewSimulation() {
  const btn = document.getElementById("runBtn");
  btn.disabled = true;
  btn.innerHTML = `<span class="spinner">⏳</span> Executing Crew...`;

  const task = document.getElementById("taskInput").value;
  const provider = document.getElementById("llmSelect").value;

  logTerminal(`🚀 Initiating Multi-Agent Ops Crew execution for: "${task}" (Provider: ${provider.toUpperCase()})`);

  // Step 1: Planner
  setNodeActive("nodePlanner", true);
  logTerminal("🧠 [PlannerAgent] Decomposing goal into 5 sub-agent DAG tasks...");
  await sleep(600);
  setNodeActive("nodePlanner", false);

  // Step 2: Parallel Fanout
  setNodeActive("nodeData", true);
  setNodeActive("nodeML", true);
  setNodeActive("nodeResearch", true);
  logTerminal("📊 [DataAgent] Processing sales metrics CSV & customer feedback JSON...");
  logTerminal("🤖 [MLAgent] Fitting linear trend regression and calculating churn correlations...");
  logTerminal("🔍 [ResearchAgent] Querying RAG VectorStore for B2B SaaS metric benchmarks...");
  await sleep(1000);
  setNodeActive("nodeData", false);
  setNodeActive("nodeML", false);
  setNodeActive("nodeResearch", false);

  // Step 3: Reviewer
  setNodeActive("nodeReviewer", true);
  logTerminal("🛡️ [ReviewerAgent] Auditing outputs for numerical consistency and hallucination risk...");
  await sleep(700);
  setNodeActive("nodeReviewer", false);

  // Step 4: Report
  setNodeActive("nodeReport", true);
  logTerminal("📝 [ReportAgent] Compiling executive Markdown report with verified recommendations...");
  await sleep(600);
  setNodeActive("nodeReport", false);

  logTerminal("🎉 Multi-Agent Ops Crew execution finished with 100/100 Quality Score!");

  // Render report
  renderFinalReport(provider);

  btn.disabled = false;
  btn.innerHTML = `<span>▶</span> Execute Multi-Agent Ops Crew`;
}

function renderFinalReport(provider) {
  const reportHTML = `# Executive AI Data Analysis & Growth Automation Report

**Generated by Multi-Agent Ops Crew**  
**LLM Engine**: \`${provider.toUpperCase()}\`  
**Audit Quality Score**: \`100/100\` (\`APPROVED\`)  

---

## 1. Key Business Financial Metrics
- **Total Revenue (YTD)**: \`$1,489,000.00\`
- **Total Marketing Spend**: \`$319,500.00\`
- **Overall Marketing ROI**: \`366.04%\`
- **Average Customer Acquisition Cost (CAC)**: \`$75.42\`
- **Average Monthly Churn Rate**: \`2.62%\`
- **Average Net Promoter Score (NPS)**: \`44.6\`

---

## 2. Machine Learning Predictive Insights
- **Model Architecture**: \`Linear Trend Regression & Feature Attribution Engine\`
- **Model R² Accuracy**: \`0.94\`
- **Q2 Revenue Forecast**: \`$612,450.00\`
- **Projected Monthly Growth Rate**: \`12.4%\`

### Primary Churn Drivers (Correlation Matrix)
1. **Net Promoter Score**: \`-0.88\` (Strongest Inverse Retention Driver)
2. **Customer Acquisition Cost**: \`0.42\`
3. **Marketing Spend**: \`-0.15\`

---

## 3. Market Benchmark Comparison
| Metric | Ops Crew Observed | SaaS Industry Benchmark 2026 | Variance Status |
| :--- | :--- | :--- | :--- |
| **NPS** | \`44.6\` | \`38.0 (Median) / 55.0 (Top)\` | 🟢 Above Median |
| **Monthly Churn** | \`2.62%\` | \`2.0%\` | 🟡 Near Target |
| **CAC Payback** | \`11.5 Months\` | \`12.0 Months\` | 🟢 Healthy |

---

## 4. Strategic Recommendations
1. **Focus Scaling on North America**: Generates top LTV with low CAC ($76.50).
2. **Localized Onboarding in Latin America**: High CAC relative to revenue requires self-serve onboarding.
3. **Invest in NPS Drivers**: Product satisfaction is the single strongest lever reducing customer churn.
`;

  document.getElementById("reportViewer").innerHTML = reportHTML.replace(/\n/g, '<br>');
  document.getElementById("metricScore").textContent = "100/100";
  document.getElementById("metricStatus").textContent = "APPROVED";
  document.getElementById("metricHallucination").textContent = "0";
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
